### ISSUE TITLE
got compiler error with ./cross_compile_ffmpeg.sh --build-intel-qsv=y

### ISSUE THREAD

**Issue by feedzapper** [rdp/ffmpeg-windows-build-helpers#104]
Start to run the Script with INTEL QSV support. 
I got an compiler error with the ./cross_compile_ffmpeg.sh --build-intel-qsv=y
What is going wrong ? Maybe there are missing some files ?

Log :
In file included from /home/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/stdio.h:991:0,
                 from src/mfx_plugin_hive.h:39,
                 from src/mfx_load_plugin.h:34,
                 from src/mfx_dispatcher.h:39,
                 from src/main.cpp:34:
/home/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/sec_api/stdio_s.h:32:72: error: conflicting declaration of 'int sscanf(const char*, const char*, ...)' with 'C' linkage
   _CRTIMP int __cdecl sscanf_s(const char *_Src,const char *_Format,...);
                                                                        ^
In file included from src/mfx_plugin_hive.h:39:0,
                 from src/mfx_load_plugin.h:34,
                 from src/mfx_dispatcher.h:39,
                 from src/main.cpp:34:
/home/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/stdio.h:227:5: note: previous declaration with 'C++' linkage
 int sscanf(const char *__source, const char *__format, ...)
     ^
make: *** [src/main.lo] Fehler 1

**Comment by rkantos** [comment]
Ha... You made it before me, I was just starting to write a report.! I've been trying to compile for about 3hrs now and been getting pretty much the same error. For me it looks the problem might be in mfx_dispatch


My error is not completely the same. I also tried to compile with another machine, although both were running Ubuntu 14.04 LTS.  I think this might be related to: https://github.com/lu-zero/mfx_dispatch/issues/15

[code]     ^
In file included from /home/rkan/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/include/stdio.h:991:0,
                 from src/mfx_plugin_hive.h:39,
                 from src/mfx_load_plugin.h:34,
                 from src/mfx_dispatcher.h:39,
                 from src/main.cpp:34:
/home/rkan/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/include/sec_api/stdio_s.h:32:72: error: conflicting declaration of 'int sscanf(const char*, const char*, ...)' with 'C' linkage
   _CRTIMP int __cdecl sscanf_s(const char *_Src,const char *_Format,...);
                                                                        ^
In file included from src/mfx_plugin_hive.h:39:0,
                 from src/mfx_load_plugin.h:34,
                 from src/mfx_dispatcher.h:39,
                 from src/main.cpp:34:
/home/rkan/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/include/stdio.h:227:5: note: previous declaration with 'C++' linkage
 int sscanf(const char *__source, const char *__format, ...)
     ^
Makefile:620: recipe for target 'src/mfx_load_plugin.lo' failed
make: *** [src/mfx_load_plugin.lo] Error 1
make: *** Odotetaan keskeneräisiä töitä....
Makefile:620: recipe for target 'src/main.lo' failed
make: *** [src/main.lo] Error 1
In file included from /home/rkan/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/include/stdio.h:991:0,
                 from src/mfx_plugin_hive.h:39,
                 from src/mfx_load_plugin.h:34,
                 from src/mfx_dispatcher.h:39,
                 from src/mfx_dispatcher.cpp:31:
/home/rkan/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/include/sec_api/stdio_s.h:32:72: error: conflicting declaration of 'int sscanf(const char*, const char*, ...)' with 'C' linkage
   _CRTIMP int __cdecl sscanf_s(const char *_Src,const char *_Format,...);
                                                                        ^
In file included from src/mfx_plugin_hive.h:39:0,
                 from src/mfx_load_plugin.h:34,
                 from src/mfx_dispatcher.h:39,
                 from src/mfx_dispatcher.cpp:31:
/home/rkan/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/include/stdio.h:227:5: note: previous declaration with 'C++' linkage
 int sscanf(const char *__source, const char *__format, ...)
     ^
Makefile:620: recipe for target 'src/mfx_dispatcher.lo' failed
make: *** [src/mfx_dispatcher.lo] Error 1
[/code]

**Comment by rdp** [comment]
OK it did compile for me OK just now, could you give me a bit more of a log
here? is it failing during mfx dispatch or ffmpeg?

**Comment by rkantos** [comment]
Dunno what happened with the output now, since it seems again to be different.. 

Currently trying another build with:
./cross_compile_ffmpeg.sh --gcc-cpu-count=3 --disable-nonfree=n --sandbox-ok=y --git-get-latest=y --prefer-stable=n --build-ffmpeg-shared=y --build-ffmpeg-static=n --build-intel-qsv=y --compiler-flavors=win64 | tee -a "ffmpeg2.log"

ti 12.1.2016 22.15.37 +0000
     ##################### Welcome ######################
  Welcome to the ffmpeg cross-compile builder-helper script.
  Downloads and builds will be installed to directories within /home/rkan/ffmpeg/ffmpeg-windows-build-helpers/sandbox
  If this is not ok, then exit now, and cd to the directory where you'd
  like them installed, then run this script again from there.
  NB that once you build your compilers, you can no longer rename/move
  the sandbox directory, since it will have some hard coded paths in there.
  You can, of course, rebuild ffmpeg from within it, etc.
Would you like to include non-free (non GPL compatible) libraries, like many high quality aac encoders [libfdk_aac]
The resultant binary may not be distributable, but can be useful for in-house use. Include these non-free-license libraries [y/N]?What version of MinGW-w64 would you like to build or update?
  1. Both Win32 and Win64
  2. Win32 (32-bit only)
  3. Win64 (64-bit only)
  4. Exit
Input your choice [1-4]: starting to download and build cross compile version of gcc [requires working internet access] with thread count 3...

Done building (or already built) MinGW-w64 cross-compiler(s) successfully...
ti 12.1.2016 22.15.40 +0000
**************Building 64-bit ffmpeg...
Updating to latest dlfcn-win32 git version [origin/master]...
Already up-to-date.
this pull got no new upstream changes, not forcing re-configure...
already configured dlfcn-win32
already did make dlfcn-win32
already configured zlib-1.2.8
already did make zlib-1.2.8
patch bzip2_cross_compile.diff already applied
already did make bzip2-1.0.6
already configured libpng-1.5.18
already did make libpng-1.5.18
already configured gmp-6.0.0
already did make gmp-6.0.0
already configured nettle-2.7.1
already did make nettle-2.7.1
already configured libiconv-1.14
already did make libiconv-1.14
already configured gnutls-3.3.19
already did make gnutls-3.3.19
already configured gnutls-3.3.19
already did make gnutls-3.3.19
already did make frei0r-plugins-1.4
already configured libsndfile-1.0.25
already did make libsndfile-1.0.25
already configured libbs2b-3.1.0
already did make libbs2b-3.1.0
already configured wavpack-4.70.0
already did make wavpack-4.70.0
Updating to latest dcadec_git git version [origin/master]...
Already up-to-date.
this pull got no new upstream changes, not forcing re-configure...
already did make dcadec_git
already did make game-music-emu-0.6.0
already configured libwebp-0.4.3
already did make libwebp-0.4.3
patch utv.diff already applied
already did make utvideo-12.2.1
patch libgsm.patch already applied
already installed gsm
already configured SDL-1.2.15
already did make SDL-1.2.15
patch opus11.patch already applied
already configured opus-1.1
already did make opus-1.1
already configured opencore-amr-0.1.3
already did make opencore-amr-0.1.3
already configured vo-amrwbenc-0.1.2
already did make vo-amrwbenc-0.1.2
already configured libogg-1.3.1
already did make libogg-1.3.1
already configured speex-1.2rc1
already did make speex-1.2rc1
already configured libvorbis-1.3.4
already did make libvorbis-1.3.4
already configured libtheora-1.2.0alpha1
already did make libtheora-1.2.0alpha1
already configured orc-0.4.18
already did make orc-0.4.18
already configured orc-0.4.18
already did make orc-0.4.18
already configured schroedinger-1.0.11
already did make schroedinger-1.0.11
already configured freetype-2.5.5
already did make freetype-2.5.5
already configured expat-2.1.0
already did make expat-2.1.0
already configured libxml2-2.9.2
already did make libxml2-2.9.2
already configured libbluray-0.7.0
already did make libbluray-0.7.0
already configured libjpeg-turbo-1.4.0
already did make libjpeg-turbo-1.4.0
already configured generic
already did make generic
not svn Updating xavs since usually svn repo's aren't updated frequently enough...
already configured xavs
already did make xavs
already did make soxr-0.1.0-Source
Doing git fetch x264 in case it affects the desired branch [origin/stable]
Already up-to-date.
~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/x264 ~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/x264
git checkout'ing origin/stable
Already up-to-date.
~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/x264
this pull got no new upstream changes, not forcing re-configure...
already configured x264
already did make x264
doing hg pull -u x265
pulling from https://bitbucket.org/multicoreware/x265
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
still at hg 000912461b14516aec81f913abb397b850c988a8 x265
already did make source
Doing git fetch openh264 in case it affects the desired branch [24916a652ee5d3]
Already up-to-date.
~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/openh264 ~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/openh264
Already up-to-date.
~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/openh264 ~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/openh264
git checkout'ing 24916a652ee5d3
Already up-to-date.
~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/openh264
this pull got no new upstream changes, not forcing re-configure...
already did make openh264
patch lame3.patch already applied
already configured lame-3.99.5
already did make lame-3.99.5
already configured twolame-0.3.13
already did make twolame-0.3.13
Doing git fetch vid.stab in case it affects the desired branch [430b4cffeb]
Already up-to-date.
~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/vid.stab ~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/vid.stab
git checkout'ing 430b4cffeb
M       CMakeLists.txt
Already up-to-date.
~/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/vid.stab
this pull got no new upstream changes, not forcing re-configure...
already did make vid.stab
already configured libcaca-0.99.beta18
already did make libcaca-0.99.beta18
already configured libmodplug-0.8.8.5
already did make libmodplug-0.8.8.5
patch zvbi-win32.patch already applied
patch zvbi-ioctl.patch already applied
already configured zvbi-0.2.35
already did make src
already configured libvpx-1.4.0
already did make libvpx-1.4.0
already configured vo-aacenc-0.1.3
already did make vo-aacenc-0.1.3
Updating to latest libilbc_git git version [origin/master]...
Already up-to-date.
this pull got no new upstream changes, not forcing re-configure...
already configured libilbc_git
already did make libilbc_git
already configured fontconfig-2.11.1
already did make libilbc_git
already configured fontconfig-2.11.1
already did make fontconfig-2.11.1
patch fribidi.diff already applied
already configured fribidi-0.19.4
already did make fribidi-0.19.4
already configured libass-0.13.1
already did make libass-0.13.1
already configured openjpeg-1.5.2
already did make openjpeg-1.5.2
Updating to latest mfx_dispatch_git git version [origin/master]...
Already up-to-date.
this pull got no new upstream changes, not forcing re-configure...
already configured mfx_dispatch_git

making /home/rkan/ffmpeg/ffmpeg-windows-build-helpers/sandbox/x86_64/mfx_dispatch_git as $ PATH=/home/rkan/ffmpeg/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:/$

depbase=`echo src/main.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile x86_64-w64-mingw32-g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.7\" -DPACKAGE_STRING=\"libmfx\ 1.7\" -DPACK$
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  x86_64-w64-mingw32-g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.7\" "-DPACKAGE_STRING=\"libmfx 1.7\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE$
depbase=`echo src/mfx_dispatcher.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile x86_64-w64-mingw32-g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.7\" -DPACKAGE_STRING=\"libmfx\ 1.7\" -DPACK$
mv -f $depbase.Tpo $depbase.Plo
depbase=`echo src/mfx_load_plugin.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CXX   --mode=compile x86_64-w64-mingw32-g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.7\" -DPACKAGE_STRING=\"libmfx\ 1.7\" -DPACK$
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  x86_64-w64-mingw32-g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.7\" "-DPACKAGE_STRING=\"libmfx 1.7\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE$
libtool: compile:  x86_64-w64-mingw32-g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.7\" "-DPACKAGE_STRING=\"libmfx 1.7\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE$
Makefile:620: recipe for target 'src/mfx_dispatcher.lo' failed
Makefile:620: recipe for target 'src/main.lo' failed
Makefile:620: recipe for target 'src/mfx_load_plugin.lo' failed

**Comment by rkantos** [comment]
>Dunno what happened with the output now, since it seems again to be different..

>Currently trying another build with:
>./cross_compile_ffmpeg.sh --gcc-cpu-count=4 --disable-nonfree=n --sandbox-ok=y --git-get-latest=y -->prefer-stable=n --build-ffmpeg-shared=y --build-ffmpeg-static=n --build-intel-qsv=y --compiler->flavors=win64 | tee -a "ffmpeg2.log"

>EDIT: log output changed, wrong building machine.., which seems ok now
>ffmpeg2.log (1).txt

I updated the logfile. The same errors come up also when ran with the commands shown above, so no help there.

**Comment by rdp** [comment]
that log file doesn't show failures? I assume if you nuke your sandbox and start over -> same failure message?

**Comment by rkantos** [comment]
Line 249-250
>make: *** [src/mfx_dispatcher.lo] Error 1
>make: *** [src/mfx_load_plugin.lo] Error 1

**Comment by rdp** [comment]
OK I did bump the mingw-w64 version to "git" just recently, wonder if that
did it...
To revert it, for now (assuming you don't need "dshow" input in the near
future) modify the script slightly to not say --mingw-w64-version=git
(remove that) and see if that makes a difference please?

**Comment by rdp** [comment]
--mingw-w64-ver=git that is

**Comment by feedzapper** [comment]
I removed the --mingw-w64-ver=git entry from the script,
but the output here is always the same ... :

./cross_compile_ffmpeg.sh --build-intel-qsv=y
Mi 13. Jan 10:27:36 CET 2016
     ##################### Welcome ######################
  Welcome to the ffmpeg cross-compile builder-helper script.
  Downloads and builds will be installed to directories within /home/freetz/ffmpeg-windows-build-helpers/sandbox
  If this is not ok, then exit now, and cd to the directory where you'd
  like them installed, then run this script again from there.
  NB that once you build your compilers, you can no longer rename/move
  the sandbox directory, since it will have some hard coded paths in there.
  You can, of course, rebuild ffmpeg from within it, etc.
Would you like to include non-free (non GPL compatible) libraries, like many high quality aac encoders [libfdk_aac]
The resultant binary may not be distributable, but can be useful for in-house use. Include these non-free-license libraries [y/N]?y
What version of MinGW-w64 would you like to build or update?
  1. Both Win32 and Win64
  2. Win32 (32-bit only)
  3. Win64 (64-bit only)
  4. Exit
Input your choice [1-4]: 3
starting to download and build cross compile version of gcc [requires working internet access] with thread count 1...

Done building (or already built) MinGW-w64 cross-compiler(s) successfully...
Mi 13. Jan 10:27:42 CET 2016
**************Building 64-bit ffmpeg...
Updating to latest dlfcn-win32 git version [origin/master]...
Already up-to-date.
this pull got no new upstream changes, not forcing re-configure...
already configured dlfcn-win32
already did make dlfcn-win32
already configured zlib-1.2.8
already did make zlib-1.2.8
patch bzip2_cross_compile.diff already applied
already did make bzip2-1.0.6
already configured libpng-1.5.18
already did make libpng-1.5.18
already configured gmp-6.0.0
already did make gmp-6.0.0
already configured nettle-2.7.1
already did make nettle-2.7.1
already configured libiconv-1.14
already did make libiconv-1.14
already configured gnutls-3.3.19
already did make gnutls-3.3.19
already did make frei0r-plugins-1.4
already configured libsndfile-1.0.25
already did make libsndfile-1.0.25
already configured libbs2b-3.1.0
already did make libbs2b-3.1.0
already configured wavpack-4.70.0
already did make wavpack-4.70.0
Updating to latest dcadec_git git version [origin/master]...
Already up-to-date.
this pull got no new upstream changes, not forcing re-configure...
already did make dcadec_git
already did make game-music-emu-0.6.0
already configured libwebp-0.4.3
already did make libwebp-0.4.3
patch utv.diff already applied
already did make utvideo-12.2.1
patch libgsm.patch already applied
already installed gsm
already configured SDL-1.2.15
already did make SDL-1.2.15
patch opus11.patch already applied
already configured opus-1.1
already did make opus-1.1
already configured opencore-amr-0.1.3
already did make opencore-amr-0.1.3
already configured vo-amrwbenc-0.1.2
already did make vo-amrwbenc-0.1.2
already configured libogg-1.3.1
already did make libogg-1.3.1
already configured speex-1.2rc1
already did make speex-1.2rc1
already configured libvorbis-1.3.4
already did make libvorbis-1.3.4
already configured libtheora-1.2.0alpha1
already did make libtheora-1.2.0alpha1
already configured orc-0.4.18
already did make orc-0.4.18
already configured schroedinger-1.0.11
already did make schroedinger-1.0.11
already configured freetype-2.5.5
already did make freetype-2.5.5
already configured expat-2.1.0
already did make expat-2.1.0
already configured libxml2-2.9.2
already did make libxml2-2.9.2
already configured libbluray-0.7.0
already did make libbluray-0.7.0
already configured libjpeg-turbo-1.4.0
already did make libjpeg-turbo-1.4.0
already configured generic
already did make generic
not svn Updating xavs since usually svn repo's aren't updated frequently enough...
already configured xavs
already did make xavs
already did make soxr-0.1.0-Source
Doing git fetch x264 in case it affects the desired branch [origin/stable]
Already up-to-date.
~/ffmpeg-windows-build-helpers/sandbox/x86_64/x264 ~/ffmpeg-windows-build-helpers/sandbox/x86_64/x264
git checkout'ing origin/stable
HEAD ist jetzt bei a0cd7d3... lavf: Use the prefixed name for pixel format enum
Already up-to-date.
~/ffmpeg-windows-build-helpers/sandbox/x86_64/x264
this pull got no new upstream changes, not forcing re-configure...
already configured x264
already did make x264
doing hg pull -u x265
Rufe von https://bitbucket.org/multicoreware/x265 ab
Suche nach Ă„nderungen
Keine Ă„nderungen gefunden
0 Dateien aktualisiert, 0 Dateien zusammengefĂĽhrt, 0 Dateien entfernt, 0 Dateien ungelĂ¶st
still at hg 000912461b14516aec81f913abb397b850c988a8 x265
already did make source
Doing git fetch openh264 in case it affects the desired branch [24916a652ee5d3]
Already up-to-date.
~/ffmpeg-windows-build-helpers/sandbox/x86_64/openh264 ~/ffmpeg-windows-build-helpers/sandbox/x86_64/openh264
git checkout'ing 24916a652ee5d3
HEAD ist jetzt bei 24916a6... Merge pull request #2215 from pengyanhai/master
Already up-to-date.
~/ffmpeg-windows-build-helpers/sandbox/x86_64/openh264
this pull got no new upstream changes, not forcing re-configure...
already did make openh264
patch lame3.patch already applied
already configured lame-3.99.5
already did make lame-3.99.5
already configured twolame-0.3.13
already did make twolame-0.3.13
Doing git fetch vid.stab in case it affects the desired branch [430b4cffeb]
Already up-to-date.
~/ffmpeg-windows-build-helpers/sandbox/x86_64/vid.stab ~/ffmpeg-windows-build-helpers/sandbox/x86_64/vid.stab
git checkout'ing 430b4cffeb
M       CMakeLists.txt
HEAD ist jetzt bei 430b4cf... version to 0.98
Already up-to-date.
~/ffmpeg-windows-build-helpers/sandbox/x86_64/vid.stab
this pull got no new upstream changes, not forcing re-configure...
already did make vid.stab
already configured libcaca-0.99.beta18
already did make libcaca-0.99.beta18
already configured libmodplug-0.8.8.5
already did make libmodplug-0.8.8.5
patch zvbi-win32.patch already applied
patch zvbi-ioctl.patch already applied
already configured zvbi-0.2.35
already did make src
already configured libvpx-1.4.0
already did make libvpx-1.4.0
already configured vo-aacenc-0.1.3
already did make vo-aacenc-0.1.3
Updating to latest libilbc_git git version [origin/master]...
Already up-to-date.
this pull got no new upstream changes, not forcing re-configure...
already configured libilbc_git
already did make libilbc_git
already configured fontconfig-2.11.1
already did make fontconfig-2.11.1
patch fribidi.diff already applied
already configured fribidi-0.19.4
already did make fribidi-0.19.4
already configured libass-0.13.1
already did make libass-0.13.1
already configured openjpeg-1.5.2
already did make openjpeg-1.5.2
Updating to latest mfx_dispatch_git git version [origin/master]...
Already up-to-date.
this pull got no new upstream changes, not forcing re-configure...
already configured mfx_dispatch_git

making /home/freetz/ffmpeg-windows-build-helpers/sandbox/x86_64/mfx_dispatch_git as $ PATH=/home/freetz/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games make  -j 1

depbase=`echo src/main.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
        /bin/bash ./libtool  --tag=CXX   --mode=compile x86_64-w64-mingw32-g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.7\" -DPACKAGE_STRING=\"libmfx\ 1.7\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libmfx\" -DVERSION=\"1.7\" -DMFX_HAVE_WINDOWS=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.  -I./include -DMINGW_HAS_SECURE_API=1   -g -O2 -MT src/main.lo -MD -MP -MF $depbase.Tpo -c -o src/main.lo src/main.cpp &&\
        mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  x86_64-w64-mingw32-g++ -DPACKAGE_NAME=\"libmfx\" -DPACKAGE_TARNAME=\"libmfx\" -DPACKAGE_VERSION=\"1.7\" "-DPACKAGE_STRING=\"libmfx 1.7\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libmfx\" -DVERSION=\"1.7\" -DMFX_HAVE_WINDOWS=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I./include -DMINGW_HAS_SECURE_API=1 -g -O2 -MT src/main.lo -MD -MP -MF src/.deps/main.Tpo -c src/main.cpp -o src/main.o
In file included from /home/freetz/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/include/stdio.h:991:0,
                 from src/mfx_plugin_hive.h:39,
                 from src/mfx_load_plugin.h:34,
                 from src/mfx_dispatcher.h:39,
                 from src/main.cpp:34:
/home/freetz/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/include/sec_api/stdio_s.h:32:72: error: conflicting declaration of 'int sscanf(const char*, const char*, ...)' with 'C' linkage
   _CRTIMP int __cdecl sscanf_s(const char *_Src,const char *_Format,...);
                                                                        ^
In file included from src/mfx_plugin_hive.h:39:0,
                 from src/mfx_load_plugin.h:34,
                 from src/mfx_dispatcher.h:39,
                 from src/main.cpp:34:
/home/freetz/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/include/stdio.h:227:5: note: previous declaration with 'C++' linkage
 int sscanf(const char *__source, const char *__format, ...)
     ^
make: *** [src/main.lo] Fehler 1
freetz@freetz-linux:~/ffmpeg-windows-build-helpers$

**Comment by feedzapper** [comment]
I forgot : 
freetz@freetz-linux:~/ffmpeg-windows-build-helpers$ lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

**Comment by rkantos** [comment]
@feedzapper 
Are you now sure you nuked the sandbox folder? I think that is required if you already have mingw built with a previous script run
@rdp dshow input is pretty much the thing I need.. I don't really need it yet, but will in a couple of months.

**Comment by rkantos** [comment]
@rdp I removed the --mingw-w64-ver=git option and guess what... done!
So what options will we have for dshow and when?

**Comment by rdp** [comment]
OK yeah I reverted it back to 4.0.4 for now.
dshow will still build "for now" until I get some changes committed in the
next couple of weeks, so you should be OK there.
When this changes I will mention it here, and also bump back to git.
Cheers!
-roger-

**Comment by feedzapper** [comment]
now ist works also for me !
I started a new clean compile with the changed script 

thanks
