### ISSUE TITLE
ERROR: Decklink API version must be >= 10.6.1.

### ISSUE THREAD

**Issue by Collisionc** [rdp/ffmpeg-windows-build-helpers#138]
In the last 2~ days or so, ffmpeg changed the version requirement for Decklink to 10.6.1, so the script breaks when it gets to that part. 

Temporarily, I just disabled Decklink, since it's not like I have any of their devices.

**Comment by Warblefly** [comment]
These DeckLink API files, compiled with mingw-w64 widl today from the latest BlackMagic SDK, seem to compile OK. I have not tested them because I do not presently have a BlackMagic device.

https://raw.githubusercontent.com/Warblefly/MultimediaTools-mingw-w64/master/DeckLinkAPI_i.c
https://raw.githubusercontent.com/Warblefly/MultimediaTools-mingw-w64/master/DeckLinkAPIVersion.h
https://raw.githubusercontent.com/Warblefly/MultimediaTools-mingw-w64/master/DeckLinkAPI.h

**Comment by rdp** [comment]
OK hopefully fixed, thanks all!
