### ISSUE TITLE
building using windows 10 linux bash shell :'aclocal-1.15' is missing on your system

### ISSUE THREAD

**Issue by MusabTM** [rdp/ffmpeg-windows-build-helpers#165]
i got failure building 32 bit gcc: this is the error in build.log

CDPATH="${ZSH_VERSION+.}:" && cd ../source/mpfr-3.1.3 && /bin/bash /mnt/g/UOW_ffmpeg/sandbox/cross_compilers/pkgs/mpfr/source/mpfr-3.1.3/missing aclocal-1.15 -I m4
/mnt/g/UOW_ffmpeg/sandbox/cross_compilers/pkgs/mpfr/source/mpfr-3.1.3/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         http://www.gnu.org/software/automake
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         http://www.gnu.org/software/autoconf
         http://www.gnu.org/software/m4/
         http://www.perl.org/
make: **\* [../source/mpfr-3.1.3/aclocal.m4] Error 127

**Comment by MusabTM** [comment]
i was able to compile on windows 10 shell by doing: 
1- **hardlink aclocal1.14 and automake1.14 with 1.15** 
```
ln /usr/bin/aclocal-1.14 /usr/bin/aclocal-1.15
ln   /usr/bin/automake-1.14  /usr/bin/automake-1.15
```
2- **add missing packages**:
 autogen  gperf and other depending on ffmpeg configurations

**Comment by rdp** [comment]
is there a package for aclocal1.15 ?

**Comment by MusabTM** [comment]
i think it comes with automake 1.15 but i could not get that install on windows 10 linux shell since it use ubuntu 14.04

**Comment by rdp** [comment]
Is this still faling?

**Comment by hvindin** [comment]
I'd suggest that this problem can be fixed by updating the version of automake that's installed in the linux on windows bash environment. From memory when the linux subsystem was first rolled out it was on a ridiculously old release of ubuntu (like nearing the end of LTS) so if you install bash for windows a long time ago you might need to reinstall it to get to Xenial.

Once on Xenial simply running

```
sudo apt-get install automake=1:1.15-4ubuntu1
```

will make sure that you have the required aclocal package.

I've installing automake 1:1.15-4 on a few windows machine and they all end up with the /usr/bin/aclocal-1.15 file created.

```
hvindin@windesk:~$ sudo apt-get install automake=1:1.15-4ubuntu1
Reading package lists... Done
Building dependency tree
Reading state information... Done
automake is already the newest version (1:1.15-4ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
hvindin@windesk:~$ realpath $(which aclocal)
/usr/bin/aclocal-1.15
```

**Comment by rdp** [comment]
newer wsl seems to work OK, please file a ticket if not the case, thanks!
