### ISSUE TITLE
Removal of "--enable-libebur128"

### ISSUE THREAD

**Issue by DeadSix27** [rdp/ffmpeg-windows-build-helpers#179]
Apparently in the latest commit (or a little earlier) the configure option

"--enable-libebur128" has been removed from ffmpeg.

> Unknown option "--enable-libebur128".
> See ./configure --help for available options.

https://github.com/FFmpeg/FFmpeg/commit/005d058f4230f3207ebcf1131df7426d4f57392f

"lavfi/loudnorm: add an internal libebur128 library"

Probably should remove that, see pull request: https://github.com/rdp/ffmpeg-windows-build-helpers/pull/180

**Comment by nschlia** [comment]
This is probably because libebur128 was changed to an internal library, thus the external build+link is no longer required, see "cus lavfi/loudnorm: add an internal libebur128 library" (https://github.com/FFmpeg/FFmpeg/commit/005d058f4230f3207ebcf1131df7426d4f57392f). So even the library build could be removed.

See change log:

version <next>:
- add internal ebur128 library, remove external libebur128 dependency

**Comment by DeadSix27** [comment]
@nschlia thats what I said in my original post see last line.

**Comment by nschlia** [comment]
Oops. Should have read more properly and kept my big mouth shut <grin> Sorry for that one.

**Comment by rdp** [comment]
OK hopefully good now :|
