### ISSUE TITLE
build_libnvenc, did it work or you just didn't like it ?

### ISSUE THREAD

**Issue by hydra3333** [rdp/ffmpeg-windows-build-helpers#224]
Hey I saw this pop into and out of existence.  Just wondering, did it work or you just didn't like it :)

```
+build_libnvenc() {
 +  if [[ ! -f $mingw_w64_x86_64_prefix/include/nvEncodeAPI.h ]]; then
 +    rm -rf nvenc # just in case :)
 +    mkdir nvenc
 +    cd nvenc
 +      echo "installing nvenc [nvidia gpu assisted encoder]"
 +      curl -4 http://developer.download.nvidia.com/assets/cuda/files/nvidia_video_sdk_6.0.1.zip -O -L --fail || exit 1
 +      unzip nvidia_video_sdk_6.0.1.zip
 +      cp nvidia_video_sdk_6.0.1/Samples/common/inc/* $mingw_w64_x86_64_prefix/include
 +    cd ..
 +  else
 +    echo "already installed nvenc"
 +  fi
 +}
```

**Comment by schmidthubert** [comment]
That's obsolete and not needed at all anymore. It's all inside ffmpeg already now because it's free now. Also the SDK has just changed to 8.0 a couple of days ago, so an update of your NVidia drivers is needed as well to get it working again. See [here](https://developer.nvidia.com/nvidia-video-codec-sdk) for more ...

**Comment by hydra3333** [comment]
ooh nice, thank you.
