### ISSUE TITLE
libmysofa build break

### ISSUE THREAD

**Issue by AndCycle** [rdp/ffmpeg-windows-build-helpers#281]
https://github.com/hoene/libmysofa/commit/cec6eea80c0c47c85fddbb6a413ce55c72addd51

as crossbuild do 
`sed -i.bak "/^install/,+1d" CMakeLists.txt` 

which breaks the current head version,

```
CMake Error at CMakeLists.txt:60:
  Parse error.  Expected "(", got quoted argument with text "lib/pkgconfig".


-- Configuring incomplete, errors occurred!
```

```
CONFIGURE_FILE(
  "${CMAKE_CURRENT_SOURCE_DIR}/libmysofa.pc.cmake"
  "${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.pc"
  @ONLY
)
  DESTINATION "lib/pkgconfig"
)
```

**Comment by AurelioSilver** [comment]
Someone else fixed it in his fork by specifing a certain revision: https://github.com/hydra3333/ffmpeg-windows-build-helpers-withOpenCL/commit/80b7bf95d894ea081ccb6468b31d5e495a8a5425

**Comment by umlaeute** [comment]
since I'm responsible for the commit, I'd like to understand the actual problem before fixing it (there's a trivial fix for it, but I'm quite hesitant to apply it)

Since i'm not much of a CMake-guy, could you post a **minimal** example to actually do a cross-build *libmysofa*?

Doing a `sed -i.bak "/^install/,+1d" CMakeLists.txt` doesn't sound like an especially clever (and robust) way to massage the build-script to your needs:
- Is this the standard way to enable cross-builds for CMake-projects?
- Where is this documented?
- What is this trying to solve?



@AurelioSilver while using a version prior to the one with the commit that breaks your build is of course a workaround, but doesn't solve the problem.

**Comment by AurelioSilver** [comment]
I know, that's why a opened an issue upstream. Was just for people who want to quick "fix" their builds for the meantime.

**Comment by umlaeute** [comment]
@AurelioSilver thanks.
@AndCycle, @AurelioSilver ouch, i was blissfully unaware that this is the ffmpeg-windows-build-helpers repo, and thought that i was commenting on hoene/libmysofa (ah, the joys of github cross-references)

**Comment by umlaeute** [comment]
a more robust replacement script should be:

    sed -e '/install(.*) *$/d' -e '/^install(/,/) *$/d'

(removing both lines consisting of complete `install(...)` stanzas and paragraphs starting with `install(` and ending with `)` (keep in mind that it's still not foolproof)

**Comment by DeadSix27** [comment]
I can't replicate this issue myself interestingly:

Can you try changing the function to:

```cmake
build_libmysofa() {
	do_git_checkout https://github.com/hoene/libmysofa.git
	cd libmysofa_git
		if [ ! -d "_build" ]; then
			mkdir _build
		fi
		cd _build
			do_cmake_and_install "-DBUILD_SHARED_LIBS:bool=off -DBUILD_TESTS=no .."
		cd ..
	cd ..
}
```
And see if that works

**Comment by Reino17** [comment]
> I have no idea why rdp sed's installs away

Because he blindly merged changes I made to my fork about 5 months ago.

**Comment by hydra3333** [comment]
beaut, I'll remove the sed from my crummy hack too then. Thanks !

**Comment by rdp** [comment]
Hopefully fixed now :)
