### ISSUE TITLE
libcaca HUNK failed error

### ISSUE THREAD

**Issue by RandomCat** [rdp/ffmpeg-windows-build-helpers#322]
I have a Ubuntu VirtualBox I use to compile FFMPEG. I used it a few months ago without issue. I ran the cross compiler script to build the 64 bit version of FFMPEG and it gives a HUNK FAILED error when cloning and patching libcaca. Please see below.

Scanning dependencies of target mysofa-static
[  4%] Building C object src/CMakeFiles/mysofa-static.dir/hdf/superblock.c.obj
[  9%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/reader.c.obj
[ 14%] Building C object src/CMakeFiles/mysofa-static.dir/hdf/dataobject.c.obj
[ 19%] Building C object src/CMakeFiles/mysofa-static.dir/hdf/btree.c.obj
[ 23%] Building C object src/CMakeFiles/mysofa-static.dir/hdf/fractalhead.c.obj
[ 28%] Building C object src/CMakeFiles/mysofa-static.dir/hdf/gunzip.c.obj
[ 33%] Building C object src/CMakeFiles/mysofa-static.dir/hdf/gcol.c.obj
[ 38%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/check.c.obj
[ 42%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/spherical.c.obj
[ 47%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/lookup.c.obj
[ 52%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/tools.c.obj
[ 57%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/kdtree.c.obj
[ 61%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/neighbors.c.obj
[ 66%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/interpolate.c.obj
[ 71%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/resample.c.obj
[ 76%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/loudness.c.obj
[ 80%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/minphase.c.obj
[ 85%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/easy.c.obj
[ 90%] Building C object src/CMakeFiles/mysofa-static.dir/hrtf/cache.c.obj
[ 95%] Building C object src/CMakeFiles/mysofa-static.dir/resampler/speex_resampler.c.obj
[100%] Linking C static library libmysofa.a
[100%] Built target mysofa-static
make installing /home/ryan/Documents/ffmpeg-windows-build-helpers/sandbox/win64/libmysofa_git as $ PATH=/home/ryan/Documents/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin:$PATH make install
[100%] Built target mysofa-static
Install the project...
-- Install configuration: ""
-- Installing: /home/ryan/Documents/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/share/libmysofa/default.sofa
-- Installing: /home/ryan/Documents/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/share/libmysofa/MIT_KEMAR_normal_pinna.sofa
-- Installing: /home/ryan/Documents/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/pkgconfig/libmysofa.pc
-- Installing: /home/ryan/Documents/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/lib/libmysofa.a
-- Installing: /home/ryan/Documents/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32/include/mysofa.h
Downloading (via git clone) libcaca_git from https://github.com/cacalabs/libcaca.git
Cloning into 'libcaca_git.tmp'...
remote: Counting objects: 13719, done.
remote: Total 13719 (delta 0), reused 0 (delta 0), pack-reused 13719
Receiving objects: 100% (13719/13719), 4.06 MiB | 2.61 MiB/s, done.
Resolving deltas: 100% (10506/10506), done.
Checking connectivity... done.
done git cloning to libcaca_git
doing git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Updating to latest libcaca_git git version [origin/master]...
Already up-to-date.
fetched no code changes, not forcing reconfigure for that...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2179  100  2179    0     0   698k      0 --:--:-- --:--:-- --:--:--  698k
applying patch libcaca_git_stdio-cruft.diff
patching file caca/figfont.c
Hunk #1 FAILED at 637.
1 out of 1 hunk FAILED -- saving rejects to file caca/figfont.c.rej
patching file caca/string.c
Hunk #3 FAILED at 595.
1 out of 3 hunks FAILED -- saving rejects to file caca/string.c.rej

**Comment by Reino17** [comment]
https://github.com/Reino17/ffmpeg-windows-build-helpers/commit/730ecc5708e67e6f1265148e06f51977fe317481

**Comment by RandomCat** [comment]
I'm compiling in a Linux environment. It looks like those files were updated in the Windows version? I tried copying the 2 files into my environment but it still didn't work.

**Comment by nschlia** [comment]
Same here, happened yesterday ar 9:00 (CET), compile runs under Debian 9 (using Jenkins):
```
09:11:53 Von https://github.com/cacalabs/libcaca
09:11:53    da28e96..5f0ec21  master     -> origin/master
09:11:53 doing git checkout master
09:11:53 Bereits auf 'master'
09:11:53 Ihr Branch ist zu 'origin/master' um 1 Commit hinterher, und kann vorgespult werden.
09:11:53   (benutzen Sie "git pull", um Ihren lokalen Branch zu aktualisieren)
09:11:53 Updating to latest libcaca_git git version [origin/master]...
09:11:53 Aktualisiere da28e96..5f0ec21
09:11:53 Fast-forward
09:11:53  XCode/libcacaXCode.xcodeproj/project.pbxproj |   2 -
09:11:53  caca/Makefile.am                             |   7 -
09:11:53  caca/attr.c                                  |  20 ---
09:11:53  caca/box.c                                   |  13 --
09:11:53  caca/caca.c                                  |   6 -
09:11:53  caca/caca.h                                  | 204 +---------------------
09:11:53  caca/canvas.c                                |  22 ---
09:11:53  caca/charset.c                               |  12 --
09:11:53  caca/codec/export.c                          |   4 -
09:11:53  caca/codec/import.c                          |  15 --
09:11:53  caca/conic.c                                 |  13 --
09:11:53  caca/dither.c                                |  51 ------
09:11:53  caca/figfont.c                               |   9 -
09:11:53  caca/file.c                                  |  16 --
09:11:53  caca/font.c                                  |  15 --
09:11:53  caca/frame.c                                 |  14 --
09:11:53  caca/legacy.c                                | 250 ---------------------------
09:11:53  caca/libcaca.vcxproj                         |   1 -
09:11:53  caca/libcaca.vcxproj.filters                 |   1 -
09:11:53  caca/line.c                                  |  15 --
09:11:53  caca/string.c                                |  29 ----
09:11:53  caca/transform.c                             |  13 --
09:11:53  caca/triangle.c                              |  14 --
09:11:53  cxx/Makefile.am                              |   5 -
09:11:53  doc/Makefile.am                              |   1 -
09:11:53  25 files changed, 1 insertion(+), 751 deletions(-)
09:11:53  delete mode 100644 caca/legacy.c
09:11:53 got upstream changes, forcing re-configure.
09:11:53 Lösche already_configured_58a59d47b023a8dac666d4ae48360878-
09:11:53 Lösche already_ran_make_2e129ec63c8da0f3864e49bb71f0e2ce-
09:11:53 Lösche already_ran_make_install_ea646e234883524f686e741be719c06d-
09:11:53 Lösche caca/caca.h.bak
09:11:53 Lösche caca/caca0.h.bak
09:11:53 Lösche caca/caca_conio.h.bak
09:11:53 Lösche caca/caca_debug.h.bak
09:11:53 Lösche caca/caca_internals.h.bak
09:11:53 Lösche caca/caca_prof.h.bak
09:11:53 Lösche caca/caca_stubs.h.bak
09:11:53 Lösche caca/caca_types.h.bak
09:11:53 Lösche caca/codec/.dirstamp
09:11:53 Lösche caca/driver/.dirstamp
09:11:53 Lösche libcaca_git_stdio-cruft.diff
09:11:53 Lösche libcaca_git_stdio-cruft.diff.done
09:11:53   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
09:11:53                                  Dload  Upload   Total   Spent    Left  Speed
09:11:53 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2179  100  2179    0     0  79392      0 --:--:-- --:--:-- --:--:-- 79392
09:11:53 applying patch libcaca_git_stdio-cruft.diff
09:11:53 patching file caca/figfont.c
09:11:53 Hunk #1 FAILED at 637.
09:11:53 1 out of 1 hunk FAILED -- saving rejects to file caca/figfont.c.rej
09:11:53 patching file caca/string.c
09:11:53 Hunk #3 FAILED at 595.
09:11:53 1 out of 3 hunks FAILED -- saving rejects to file caca/string.c.rej
09:11:53 Build step 'Shell ausführen' marked build as failure
09:11:54 Finished: FAILURE

```

**Comment by RandomCat** [comment]
Giving it a try now. I'll follow up when I'm done. On a side note I noticed I am no longer prompted to ask if I want to enable or disable non-free libs. It seems the flag that controls it needs to be commented out first. Was there a change made so users have to manually comment that flag out to get prompted? The main reason I use your amazing scripts is so I can easily compile those libs. I'm sure others would prefer to have it commented out by default. Just a suggestion.

**Comment by Reino17** [comment]
> It looks like those files were updated in the Windows version?

What Windows version? Of what?
I'm downloading and compiling exactly the same libcaca as you and all I did was update the "stdio-cruft" patch because of the latest commit in the libcaca repo.
And because you're on Ubuntu you don't even need this patch, so you could've just commented it out.
> I went ahead and pinned it to a "known working version" 780f181

I present you an easy fix, yet you revert libcaca to a previous commit. I really don't understand this.

**Comment by vargas1010** [comment]
> I present you an easy fix, yet you revert libcaca to a previous commit. I really don't understand this.

Calm down there buddy. No need to get defensive. I am also having the same issue and unclear what the fix is based on your first comment. 

Your very first comment ("Reino17/ffmpeg-windows-build-helpers@730ecc5") was just a link to a version with zero context. It had a diff of two files in the Cygwin/Windows version of your script with lots of changes. While you understand what you meant, we are not you. You also seem to have misunderstood what was said. Let's not assume what people mean and instead keep the comment focused on understanding rather than unhelpful communication. 

> And because you're on Ubuntu you don't even need this patch, so you could've just commented it out.

If it isn't needed then why is your linux script cloning and trying to compile it? Typically one uses directives to comment out sections not applicable to the current environment. Your scripts are advertised as automating the whole process, so don't expect people to understand the project the way you do. If they have replicated the environment your faq says they need, then it is understandable if they do not understand why it isn't working. 

> seems to be something of a moving target.  I went ahead and pinned it to a
"known working version" 780f181 let me know if it doesn't work, thanks!

This comment actually communicated a fix and how to implement it. It also seemed to bypass the issue. However, it seems the libxavs repo is down for maintenance so the build stops when trying to clone the repository. I'm not sure who RDP is, but maybe you need to talk to them since they are the one who posted this comment as a fix. 

If using a different version of libcaca isn't the true fix, then I'm unsure what to do. Your latest comment focused more on picking apart people's comments to point out something you felt they said wrong which doesn't actually address the problem. Thank you to everyone who has tried to fix this issue. I also appreciate you writing these scripts.

**Comment by Reino17** [comment]
> Calm down there buddy.

Oh I'm calm. I'm just expressing my confusion.
> Your very first comment ("Reino17/ffmpeg-windows-build-helpers@730ecc5") was just a link to a version with zero context.

That comment was actually directed @rdp and I thought he would understand it all.
I agree I could've added some more info, so [I just did](https://github.com/Reino17/ffmpeg-windows-build-helpers/commit/23a1ff4d49ea69ba9f0d2907d00345c5fa8925a6).
> It had a diff of two files in the Cygwin/Windows version of your script with lots of changes.

The fact that I compile on Windows is totally irrelevant in this case. The patch is universal.
It's (probably) because I created this patch with `git diff` that it looks like it contains lots of changes, but with `diff -ur` it would look like this:
```diff
--- libcaca_git_stdio-cruft.diff.bak	2018-05-06 01:22:01.656250000 +0200
+++ libcaca_git_stdio-cruft.diff	2018-05-06 01:34:01.312500000 +0200
@@ -1,10 +1,12 @@
 diff -ur caca/figfont.c.bak caca/figfont.c
---- caca/figfont.c.bak	2017-05-13 22:44:04.812500000 +0200
-+++ caca/figfont.c	2017-05-13 22:52:57.375000000 +0200
-@@ -637,31 +637,6 @@
- }
+--- caca/figfont.c.bak	2018-05-06 01:24:36.562500000 +0200
++++ caca/figfont.c	2018-05-06 01:26:20.500000000 +0200
+@@ -635,29 +635,3 @@
  
- /*
+     return 0;
+ }
+-
+-/*
 - * Functions for the mingw32 runtime
 - */
 -
@@ -29,13 +31,9 @@
 -#   endif
 -#endif
 -
--/*
-  * XXX: The following functions are aliases.
-  */
- 
 diff -ur caca/string.c.bak caca/string.c
---- caca/string.c.bak	2017-05-13 22:44:04.859375000 +0200
-+++ caca/string.c	2017-05-13 22:53:04.890625000 +0200
+--- caca/string.c.bak	2018-05-06 01:24:36.593750000 +0200
++++ caca/string.c	2018-05-06 01:27:25.843750000 +0200
 @@ -36,16 +36,6 @@
  #include "caca.h"
  #include "caca_internals.h"
@@ -67,10 +65,12 @@
      buf[bufsize - 1] = '\0';
  
      ret = caca_put_str(cv, x, y, buf);
-@@ -611,26 +595,6 @@
- }
+@@ -609,24 +593,3 @@
  
- /*
+     return 0;
+ }
+-
+-/*
 - * Functions for the mingw32 runtime
 - */
 -
@@ -90,7 +90,3 @@
 -#   endif
 -#endif
 -
--/*
-  * XXX: The following functions are aliases.
-  */
- 
```
...just a re-indexing (or a "moving target" as Roger calls it).

> You also seem to have misunderstood what was said.

Enlighten me, please.
> If it isn't needed then why is your linux script cloning and trying to compile it?

Because I actually need the WinXP compatibility.
> Typically one uses directives to comment out sections not applicable to the current environment.

I don't believe it's harmful to Linux users to apply this patch and compile libcaca.
> ...so don't expect people to understand the project the way you do.

I do expect Roger to understand.
> I'm not sure who RDP is

Uhm, "_github.com/**rdp**/ffmpeg-windows-build-helpers_"?
> If using a different version of libcaca isn't the true fix, then I'm unsure what to do.

- Open '_patches/libcaca_git_stdio-cruft.diff_' in your text-editor and replace everything with the `diff -ur`-code above.
- Or you could just ignore the patch, because you're on Ubuntu anyway:
```diff
-    apply_patch file://$patch_dir/libcaca_git_stdio-cruft.diff # Fix WinXP incompatibility.
+    #apply_patch file://$patch_dir/libcaca_git_stdio-cruft.diff # Fix WinXP incompatibility.
```
- Or you could update '_cross_compile_ffmpeg.sh_':
```diff
-    apply_patch file://$patch_dir/libcaca_git_stdio-cruft.diff # Fix WinXP incompatibility.
+    apply_patch file://$patch_dir/libcaca_git_stdio-cruft.patch -p1 # Fix WinXP incompatibility.
```
...and use [my patch](https://github.com/Reino17/ffmpeg-windows-build-helpers/blob/master/patches/libcaca_git_stdio-cruft.patch).

**Comment by rdp** [comment]
Yes you're right I should have used the new patch but was trying to hurry something out the door so just reverted.  I've attempted to fix my flub now, cheers!
