### ISSUE TITLE
svt-av1 patch not working

### ISSUE THREAD

**Issue by EsmeraldaQuintero** [rdp/ffmpeg-windows-build-helpers#413]
I'm compiling the win64 version with svt-av1 but I'm having a fatal error because the `#include "Windows.h"` has the `W` capitalized.

Reviewing... I notice that `git apply $patch_dir/SVT-AV1-Windows-lowercase.patch` is not working, so I change that line for `apply_patch file://$patch_dir/SVT-AV1-Windows-lowercase.patch -p1`... that works for me.

I don't know if that happens with the another libraries.

-_-_-_-_-_- EDIT
I also change this line:
`git apply 0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch`
For this:
`apply_patch file://$patch_dir/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch -p1`

And I added the patch into the patches folder.
`https://raw.githubusercontent.com/OpenVisualCloud/SVT-AV1/master/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch`

**Comment by krakow10** [comment]
I'm the one who added the SVT codecs to the main script.  Making the SVT codecs individually compile into ffmpeg successfully is as far as I could get, SVT-AV1 and SVT-VP9 do not produce video output when I try to use them which is why they are disabled.  I expect that they don't work because they were not designed to be cross compiled yet, but I don't know a whole lot about that.  The older SVT-HEVC is the only one that works great with no codec conflicts and produces video output.

In order to try building SVT-AV1 into ffmpeg using this script:
- Delete the ffmpeg build output folder so the patches can be re-applied
In "build_ffmpeg":
- Comment out the patch for SVT-HEVC and the git apply on line 2091 and 2092
- Uncomment the "SVT-AV1 only" patch and git apply lines that are just below
- Comment out "--enable-libsvthevc" and the surrounding if statement on line 2128-2131 near "config_options"
- Comment out "--enable-libaom" just below
- Uncomment "--enable-libsvtav1"

- Uncomment build_svtav1 on line 2355 in "build_ffmpeg_dependencies"
