### ISSUE TITLE
Build fails on harfbuzz

### ISSUE THREAD

**Issue by nschlia** [rdp/ffmpeg-windows-build-helpers#484]
For me build fails for both 64 and 32 versions on harfbuzz with "Cross dependency freetype2 found: NO". I don't see what's wrong. I already rm -Rf'ed the sandbox, same outcome.

Unfortuantely, I can't tell which commit caused that as it failed since 05.06.2020, in the beginning because I did not remove the '--high-bitdepth' parameter. Once removed it failed for various reason which went away, but not this:

```
15:10:16 Native C++ compiler: ccache c++ (gcc 8.2.0 "c++ (GCC) 8.2.0")
15:10:16 Cross C++ compiler: /home/jenkins/ffmpeg-windows-build-helpers/workspace/sandbox/cross_compilers/mingw-w64-i686/bin/i686-w64-mingw32-g++ (gcc 10.1.0)
15:10:16 Host machine cpu family: x86
15:10:16 Host machine cpu: x86
15:10:16 Target machine cpu family: x86
15:10:16 Target machine cpu: x86
15:10:16 Build machine cpu family: x86_64
15:10:16 Build machine cpu: x86_64
15:10:16 Compiler for C++ supports link arguments -Bsymbolic-functions: YES
15:10:16 Compiler for C++ supports arguments -fno-exceptions: YES
15:10:16 Compiler for C++ supports arguments -fno-rtti: YES
15:10:16 Compiler for C++ supports arguments -fno-threadsafe-statics: YES
15:10:16 Compiler for C++ supports arguments -fvisibility-inlines-hidden: YES
15:10:16 Library m found: YES
15:10:16 Cross dependency freetype2 found: NO (tried cmake)
15:10:16 Cross dependency freetype2 found: NO 
15:10:16 Build step 'Shell ausführen' marked build as failure
```

**Comment by rdp** [comment]
Any ideas @PeacefullyDisturbed ?

**Comment by PeacefullyDisturbed** [comment]
It looks like Harfbuzz has reversed course and re-added autotools support as well as modifying the meson.build significantly for the 2.7.1 release to lower the required Meson version.

I added a quick fix in #480 for meson.build to find freetype using a header check, otherwise that was failing when cross compiling.  It looks like their changes broke this again as they removed all header checks.

Honestly I think the easiest fix is to simply revert 2daf0178f444b6b3e5a9d2cfc389a85cd52afd35 so Harfbuzz is built with autotools again.  From the discussion between the maintainers in https://github.com/harfbuzz/harfbuzz/pull/2632 it seems like autotools will be kept for at least a while longer (there was a lot of internal pushback after removal).  Switching it to Meson can be probably be done again later after their meson.build has stabilized more.

**Comment by rdp** [comment]
OK good idea, care to try it now?

**Comment by nschlia** [comment]
> 
> 
> OK good idea, care to try it now?

Build is running...

**Comment by nschlia** [comment]
Sorry, but now the build fails early (it's a full rebuild, I deleted the sandbox):

```
10:25:43 doing hg clone x265
10:25:44 Abort: HTTP Authorization Required for https://bitbucket.org/multicoreware/x265
10:25:44 Build step 'Shell ausführen' marked build as failure
```
When I open https://bitbucket.org/multicoreware/x265 I get 

Repository unavailable
Bitbucket no longer supports Mercurial repositories.

**Comment by nschlia** [comment]
Appears that the bitbucket Mercurial repositories are gone. Maybe you could switch to the Github mirror at https://github.com/videolan/x265

**Comment by PeacefullyDisturbed** [comment]
There is also the Videolan hosted HG mirror (http://hg.videolan.org/x265) which doesn't require changing it to Git, just changing the URL.

I'm surprised x265 didn't move to Heptapod yet, it seems like they have no official repository right now.

**Comment by rdp** [comment]
OK fixed x265 location (I think).  I was able to build harfbuzz just
now, does it still fail for you?

**Comment by nschlia** [comment]
Build is still running, but looks good. x265 was built, and the 32 bit compile ran through. Currently it's making the 64 bit binaries, I guess that won't fail.

BTW, it still states "doing hg clone x265" but I guess you just forgot to update the messages.

**Comment by nschlia** [comment]
23:21:19 Finished: SUCCESS

That was a complete rebuild of both 32 and 64 bit. This is OK now, I'll close this issue :)
