### ISSUE TITLE
Where is the script?

### ISSUE THREAD

**Issue by markfilipak** [rdp/ffmpeg-windows-build-helpers#488]
On this page:
https://github.com/rdp/ffmpeg-windows-build-helpers#readme
there is text with this title:
"ffmpeg-windows-build-helpers".
The very first line reads:
"This helper script..."
What is the antecedent of the word "This"?

In normal English, the preposition "This" would be a forward reference to the body of the script, or to a link to the body of the script that is separated from the clause "This helper script" by a colon or a comma. Or, less desirable, the preposition "This" would be a backward reference, however, in this case, that's not possible because the "This" sentence is the first sentence.

Where is the script?

**Comment by rdp** [comment]
It's a sibling to the readme file.  The main script is.  I should clear
that up...

On Friday, September 4, 2020, Mark Filipak <notifications@github.com> wrote:
> On this page:
> https://github.com/rdp/ffmpeg-windows-build-helpers#readme
> there is text with this title:
> "ffmpeg-windows-build-helpers".
> The very first line reads:
> "This helper script..."
> What is the antecedent of the word "This"?
>
> In normal English, the preposition "This" would be a forward reference to
the body of the script, or to a link to the body of the script that is
separated from the clause "This helper script" by a colon or a comma. Or,
less desirable, the preposition "This" would be preceded by such a
reference, however, in this case, that's not possible because the "This"
sentence is the first sentence.
>
> Where is the script?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/cxwbc8bmw8GNmynR-nOFFPc6pcE5774CqpT4hEyT-S_J1qIlNTjU9BoRCg2iJPuF9tJrj2DOdlRuwEPuAHXi2Z7yO-CfX_ap64tC3Tm0mw1isdkTlVjwP8VXLlu1evOetnLlU4UiXwlrTFAp7jAjfOtff37JiAXUSgSbXDPXPWDU-_cVaaiikSKLAXw07XTgU6IZ44LtEiemlaQr0CK-3YotYhY=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUD6Z3T4MC5RBBGVE73SEEKDBA5CNFSM4QY3UG4KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4KKUB6XQ.gif>

**Comment by markfilipak** [comment]
A sibling? All I see (in the whatever-it-is list above) is this:
cross_compile_ffmpeg.sh . . . . . #487 how did this ever work?
I think the '.sh' is a script -- not really sure -- and the 'cross_compile_ffmpeg' is promising, but it looks like only part of a script.
Oh, wait, ...I see. I was clicking on the wrong part of that. I was clicking on the "how did this ever work?"

Argh! Github! Code without comments is crytic enough, github makes the documentation cryptic, too.
