### ISSUE TITLE
x265 stable x265 nightly

### ISSUE THREAD

**Issue by Mister-XY** [rdp/ffmpeg-windows-build-helpers#515]
Hello, a little question, I can use --prefer-stable=y to ensure that I want a stable version. But if I do that, I get an RC1 version of x265 (which I also get as a nightly version). But I assume that version 3.4 is the stable version and not version 3.4_RC1 + 25-529cac916a7d.

**Comment by rdp** [comment]
I think all it does is checkout whatever the x265 people have tagged
as their "stable" branch...you could complain to them if you think
it's out of date, but I don't understand their system fully enough for
me to know how exactly which version to checkout (since it might
change over time on me)  Or modify the script to checkout a specific
branch maybe, instead of stable?  Let me know if you have any
questions.

**Comment by rdp** [comment]
Not much I can do to control upstream namings/tags...sorry.

**Comment by Mister-XY** [comment]
Maybe it is possible to have an option called e.g. Include "--x265-version = 3.4". Then he does a checkout of the said version. If the function is not available, then he should look for a stable version. Since the stable and the nightly version are identical.
