### ISSUE TITLE
does docker script only build x64? (docker-entry.sh)

### ISSUE THREAD

**Issue by ahmedtds** [rdp/ffmpeg-windows-build-helpers#548]
I didn't try it yet but having look at docker-entry.sh, does it only build x64 binaries?

I can just change the "win64" to "win32" to make it compile win32 I guess but it would be nice if this is mentioned in readme, or even better it would be better if it asks you about it during running like how the normal non-docker script does it. right?

thanks in advance for any clarification.

**Comment by rdp** [comment]
Interesting ideas.  I imagine most people just want the 64 bit.
Maybe I could make it more clear...

On Sunday, February 28, 2021, ahmedtds <notifications@github.com> wrote:
> I didn't try it yet but having look at docker-entry.sh, does it only
build x64 binaries?
>
> I can just change the "win64" to "win32" to make it compile win32 I guess
but it would be nice if this is mentioned in readme, or even better it
would be better if it asks you about it during running like how the normal
non-docker script does it. right?
>
> thanks in advance for any clarification.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/knpBNnR27gug2WwMBUtpiB8zGzXXO78jnDj7js1jd1DzP7OYx1A1ZTpDe-cAQoHSArtQ7CJlFDBQIroc3SuMv4aBS6vtmR6_1Hie_z9a5DXj2LKs8ePZZAVVJiVyD4XYiYxLF98b-Mb-df7eC3mldNPntx0lHe2WU8beyM8jIrFR_q7RgMic0mlP6mmfQ2YQ4DRKcnxD5UuuTd48uTE-nuNw5oY=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUGI53LPWNLSNZRT63DTBIQ7DA5CNFSM4YK6RZX2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4MGEPD2Q.gif>

**Comment by ahmedtds** [comment]
> I imagine most people just want the 64 bit.
Well, there are a lot of places who produces regular 64bit binaries, links on official ffmpeg site builds only 64bit, only reason I became aware of this script and need to build it myself is because of the lack of regular 32bit builds out there.

anyway, is changing `--compiler-flavors=win64` from `docker-entry.sh` is enough? Do I need to take care of something else?

**Comment by rdp** [comment]
The path to the executable will be win32 as well, thanks.

On Wednesday, March 3, 2021, ahmedtds <notifications@github.com> wrote:
> I imagine most people just want the 64 bit.
>
> Well, there are a lot of places who produces regular 64bit binaries,
links on official ffmpeg site builds only 64bit, only reason I became aware
of this script and need to build it myself is because of the lack of
regular 32bit builds out there.
>
> anyway, is changing --compiler-flavors=win64 from docker-entry.sh is
enough? Do I need to take care of something else?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/IfN4t3kDrM1lMZj03I-0GUfvXsXLYFBtq85eYTVvPy-m_UuZDyK7bLahd9e6p_lJAEM_PEckjY7i0-ifycO_CUdl5UKCeJLJf1saU8CL8lXHFFH1EpwIBooqvjequy3jhph5M-bWvxbJ9blcce2CdpGm5Ipk8BVeSZQn2BalCd4QkdQVyCIauxHHTW_Esg64BndivMktqlOgLJwF68xT1JShv4fvf5k6uL5KRZqKrg=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUFW5MH2E57OQPCKRUTTBYY7PA5CNFSM4YK6RZX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOF4I7MFY.gif>

**Comment by rdp** [comment]
I think this was addressed with a PR?

**Comment by ahmedtds** [comment]
I don't think so, how?

**Comment by rdp** [comment]
I'd say if you need win32 build go ahead and build it without docker for now...
