### ISSUE TITLE
libmpg123 not found

### ISSUE THREAD

**Issue by j-forster** [rdp/ffmpeg-windows-build-helpers#550]
Running on a fresh new WSL Ubuntu 20.04 on Windows, I encounter the following error:

```
...
checking use of ElectricFence malloc debugging... no
checking use of file io... lame
checking use of analyzer hooks... yes
checking for mpg123... no
checking use of external mpg123 decoder... configure: error: no, libmpg123 not found
```

Maybe I need to download the library from https://www.mpg123.de/? Where should I put the library files?

Thanks for your help!

**Comment by Smalls1652** [comment]
Ran into the same issue on an Ubuntu 20.04 VM. I was able to get past it by creating a `build_mpg()` function and calling it before `build_lame()` is ran. I just forked this repo and made that change [(Here's the comparison between the two repos)](https://github.com/rdp/ffmpeg-windows-build-helpers/compare/master...Smalls1652:master).

This actually got me through, but I've hit an issue with it building rubberband and it applying a patch:
```
doing git checkout default
M	rubberband.pc.in
Already on 'default'
Your branch is up to date with 'origin/default'.
Already up to date.
fetched no code changes, not forcing reconfigure for that...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1081  100  1081    0     0  1055k      0 --:--:-- --:--:-- --:--:-- 1055k
applying patch rubberband_git_static-lib.diff
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -ur Makefile.in.bak Makefile.in
|--- Makefile.in.bak	2017-04-27 15:44:27.859375000 +0200
|+++ Makefile.in	2017-05-23 23:10:31.531250000 +0200
--------------------------
```

That's a totally separate issue to this one though. lol

**Comment by naabtog** [comment]
Addition of `build_mpg` function should be merged to `master`.

**Comment by Smalls1652** [comment]
@naabtog I intend to make a pull request from my forked branch soon, but I did run into that same issue.

I tried to build from the 3.100 release, but that failed as well. Using 3.99 worked just fine though. I need to narrow down why the build keeps on failing.

**Comment by naabtog** [comment]
@Smalls1652 I added a link to system libraries with `ldflags` but it didn't help. Script crashes with another error.

**Comment by Reino17** [comment]
>     checking use of external mpg123 decoder... configure: error: no, libmpg123 not found

This is because for some reason `--disable-decoder` [was removed](https://github.com/rdp/ffmpeg-windows-build-helpers/commit/4f9c28d095615f546c3a3971cd03d09418c19411).

`libmpg123` really isn't necessary for the purpose of creating a `libmp3lame` encoder for `ffmpeg`.

And [as pointed out earlier](https://github.com/rdp/ffmpeg-windows-build-helpers/commit/e5f9f811c430d6fe2ab0066c966e4d5835134dfd#commitcomment-42378074)...
https://github.com/rdp/ffmpeg-windows-build-helpers/blob/dd8c4b1eeee3eddd01a318ebcc7d1ca56f360b94/cross_compile_ffmpeg.sh#L1338
...this issue has been fixed upstream for quite some time already. So it's no longer necessary.

**Comment by naabtog** [comment]
Neither does work changing `lame_svn` to older, safe revision.

**Comment by Smalls1652** [comment]
@Reino17 Interesting. I’ll play around with that portion of the script and rerun the build when I get home later. I’ll check to see if that resolves the issue. I added `libmpg123` to the build process because that resolved the issue for me.

**Comment by Rob2k9** [comment]
tried running ./cross_compile_ffmpeg.sh today and getting the same issues implamented the fix by Smalls1652 but dosent seemt o be working when i rerun the script it stops at the exact same point

**Comment by BeckerMarkus** [comment]
@Rob2k9 might be worth to mention, you also must add a call to build_mpg in build_ffmpeg_dependencies()
```
  ...
  build_libtheora # Needs libogg >= 1.1. Needs libvorbis >= 1.0.1, sdl and libpng for test, programs and examples [disabled]. Uses dlfcn.
  build_mpg
  build_libsndfile "install-libgsm" # Needs libogg >= 1.1.3 and libvorbis >= 1.2.3 for external support [disabled]. Uses dlfcn. 'build_libsndfile "install-libgsm"' to install the included LibGSM 6.10.
  ...
```

**Comment by Smalls1652** [comment]
@Reino17 

> > ```
> > checking use of external mpg123 decoder... configure: error: no, libmpg123 not found
> > ```
> 
> 
> This is because for some reason `--disable-decoder` [was removed](https://github.com/rdp/ffmpeg-windows-build-helpers/commit/4f9c28d095615f546c3a3971cd03d09418c19411).
> 
> 
> `libmpg123` really isn't necessary for the purpose of creating a `libmp3lame` encoder for `ffmpeg`.

Mmm Didn't really cross my mind about that. I totally forgot `ffmpeg` has a built-in `mp3` decoder, if I'm not mistaken. I'm running through a clean build right now with `--disable-decoder` in the config option, so that should run through without a problem.

**Comment by rdp** [comment]
OK try it now, reverted to an older version...

**Comment by naabtog** [comment]
@rdp Reverting `lame` to r6474 didn't work. I'm still having errors configuring `ffmpeg`.

**Comment by rdp** [comment]
Nuke sandbox help?  It worked for me on 20.something...

**Comment by Smalls1652** [comment]
@rdp Still failed for me with a clean sandbox folder; however, going back to @Reino17's comment and adding in `--disable-decoder` to configure was part of the solution that fixed it for me. The second thing I had to do was add in `--disable-frontend`. I've got in my fork right now under this commit: Smalls1652/ffmpeg-windows-build-helpers@d1f0892c95d72a916b5136bc3755decbde35aaa0.

Adding those two in got me to a successful build. I haven't tested `mp3` encoding/decoding yet as I currently have a bunch of media being encoded into `mp4` containers with `HEVC` and `AAC` streams. Encoding shouldn't be affected, but also decoding shouldn't as well since ffmpeg already has a `mp3` decoder built into it.

**Comment by rdp** [comment]
What os and build command line?  Glad you got it working!

On Saturday, March 20, 2021, Timothy Small ***@***.***> wrote:
> @rdp Still failed for me with a clean sandbox folder; however, going back
to @Reino17's comment and adding in --disable-decoder to configure was part
of the solution that fixed it for me. The second thing I had to do was add
in --disable-frontend. I've got in my fork right now under this commit:
***@***.***
>
> Adding those two in got me to a successful build. I haven't tested mp3
encoding/decoding yet as I currently have a bunch of media being encoded
into mp4 containers with HEVC and AAC streams. Encoding shouldn't be
affected, but also decoding shouldn't as well since ffmpeg already has a
mp3 decoder built into it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/K9T8q1cAcIM0Md9fHkDgqGnEG908SicwRMxTeRploPRxH_mrzlrq6N6QLL5E6TyNKZ26pvF9TJLtcS4O-6AZHYwFU7jWIY54i8YM5IDvwhTSPp9qTrxRo6F2QAoYjgCszJYyhABkyPq9bvumRUyxmIo31y6ylUGO85FOtuXiKo7A9ZjoBMZpPcZtdRUGrxuuu_0xB-Lc8NABR_bpHeoBx_l-PSpd9PEShz_wWlTCew=s0-d-e1-ft#https://github.com/notifications/beacon/AAADBUGUIVU354L23KLAAL3TEV3QFA5CNFSM4ZBCFRA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOF7SJ53I.gif>

**Comment by Smalls1652** [comment]
Ran it on Ubuntu 20.04 LTS and the command-line for the build I used was `./cross_compile_ffmpeg.sh --disable-nonfree=n --compiler-flavors=win64`. I can spin up another distro in a VM and run through it again if you need me to!

**Comment by naabtog** [comment]
> Nuke sandbox help?

I made a clean installation, now it works fine. Thanks a lot,
So we'll be sticking with older versions of some libraries.

**Comment by rdp** [comment]
@Smalls1652 Seemed to work OK for me just now, care to try in a fresh VM?

**Comment by Smalls1652** [comment]
@rdp Sure thing! Might take a few hours, but I'll get it started here in a few. I'll run it on Fedora Workstation 33 this time and then circle back to Ubuntu 20.04 one more time.

**Comment by Smalls1652** [comment]
@rdp **Build worked on the Ubuntu 20.04 VM on my work laptop.** I didn't have to use my fork that has `--disable-decoder --disable-frontend` in the configure options for building `lame`. That's strange how it failed on my personal laptop's VM on Saturday night and not on my work laptop's VM. I just created a new Ubuntu 20.04 VM on my personal laptop and I'll run the build on there again.

The only thing different between my work and personal laptop is that my work laptop was running through Windows 10's Hyper-V hypervisor (Not WSL) and my personal laptop was running through macOS Big Sur and VMWare Fusion's hypervisor. They were both completely fresh VMs too. That can't be the reason why at all, but just figured I'd note it. lol 😅

The Fedora Workstation 33 failed to build, but that's a whole different story and that's related to rdp/ffmpeg-windows-build-helpers#497.

**Comment by rdp** [comment]
OK I think this is resolved now?
