### ISSUE TITLE
Build fails due to changes in twolame's main branch

### ISSUE THREAD

**Issue by tsukumijima** [rdp/ffmpeg-windows-build-helpers#576]
https://github.com/njh/twolame/commit/8c474016a5eddb0237a562e7a8bfa319203c30ad

Just five hours ago, the twolame master branch was renamed to main.
Due to this effect, the build of ffmpeg fails because twolame cannot be checkedout.

The workaround is simple: just add ` twolame_git "origin/main"` to the end of https://github.com/rdp/ffmpeg-windows-build-helpers/blob/master/cross_compile_ffmpeg.sh#L1348.
I have confirmed that I can checkout again.

For your reference.

**Comment by Vangelis66** [comment]
... **harfbuzz** all over again 😠 ; what is it with this new trend of renaming the `master` branch to `main` ? Is this mandated by GitHub?

In any case, @tsukumijima, could you be kind enough to submit a **PR** with the needed fix? Thanks! 😄

**Comment by tsukumijima** [comment]
I thought about PR, but since the range of fix is narrow, I would like to have the maintainer fix it directly.

**Comment by Vangelis66** [comment]
This should be, probably, now **closed** :wink:, as a result of https://github.com/rdp/ffmpeg-windows-build-helpers/pull/577 having been merged... :+1:

**Comment by Vangelis66** [comment]
@tsukumijima 

Hi :smile: ; apologies for bringing this up here, but I just noticed you recently tried `ffmpeg` compilation via https://github.com/marierose147/ffmpeg_windows_exe_with_fdk_aac, which also uses this project as backend :+1: .
However, compilation there is currently **broken** due to https://github.com/marierose147/ffmpeg_windows_exe_with_fdk_aac/commit/f8181d1, which was necessary due to un-fixed issues in **this** project :wink: ; now that the building script has been fixed (and until it breaks again :cry: ), **that commit** has to be reverted; pinging @marierose147 :smiley_cat:

**Comment by marierose147** [comment]
@Vangelis66
Thanks. It's fixed now.
