### ISSUE TITLE
libbluray not found using pkg-config

### ISSUE THREAD

**Issue by SmoochySix4** [rdp/ffmpeg-windows-build-helpers#642]
ERROR: libbluray not found using pkg-config
[config.log](https://github.com/rdp/ffmpeg-windows-build-helpers/files/9148293/config.log)

**Comment by newcapricasean** [comment]
sudo dnf install freetype*
sudo dnf install libxml*
sudo dnf install iconv*
sudo dnf install dlfcn*

solved that problem, for me... Maybe that'll help you... Bear in mind that the install command may differ, depending upon which distribution you are using...

**Comment by cycollins** [comment]
I was trying to build ffmpeg on Raspian on a Pi5 and I got this error COMPLETELY spuriously. Independently, libbluray was installed just fine. It turned out what config means when it says you fail pkg-config is that it tried a BUNCH of tests, one of which was pkg-config and ONE of them failed. In this case it was an attempt to build and link a snippet of code that called bd_open, and the build of that snippet failed. Arguably this WAS a fail on the part of libbluray's packaging, because it failed to include an implicit dependency, namely liblzma-dev. Installed that, and I was off to the races (until the next frustrating configure fail). So be careful when configure tells you something failed pkg-config check. It simply means it couldn't even with the library in general.
