### ISSUE TITLE
compile error on ubuntu 20.04

### ISSUE THREAD

**Issue by xengine-qyt** [rdp/ffmpeg-windows-build-helpers#686]
ubuntu 20.04.5 lts x64.
build command:./cross_compile_ffmpeg.sh --build-ffmpeg-shared=y --build-ffmpeg-static=n --ffmpeg-git-checkout-version=n5.1.2

![image](https://user-images.githubusercontent.com/37919215/223361978-cf6a9f46-e1f4-4db9-9255-4502782f1f25.png)

**Comment by xengine-qyt** [comment]
> 

o ...id is 679？ it's too long time

**Comment by naabtog** [comment]
@xengine-qyt I guess @Biswa96 is talking about [this](https://github.com/lensfun/lensfun/issues/1998).

**Comment by xengine-qyt** [comment]
> 
OK  .thanks...

**Comment by catester** [comment]
I upgraded to ubuntu 22.04.2 LTS (windows bash) just for this error and it turns out it's not related to ubuntu.
It's about lensfun project being broken for cross compilers (windows builds). Until they fix it in lensfun, I am using this modification in cross_compile_ffmpeg.sh to apply the patch from https://github.com/lensfun/lensfun/issues/1998 automatically.

```sh
build_lensfun() {
  build_glib
  do_git_checkout https://github.com/lensfun/lensfun.git lensfun_git
  cd lensfun_git
    
    #MODIFY
    #Patch to fix compile problem: https://github.com/lensfun/lensfun/issues/1998
    apply_patch https://patch-diff.githubusercontent.com/raw/lensfun/lensfun/pull/1999.patch -p1
    #MODIFY

    export CMAKE_STATIC_LINKER_FLAGS='-lws2_32 -pthread'
    do_cmake "-DBUILD_STATIC=on -DCMAKE_INSTALL_DATAROOTDIR=$mingw_w64_x86_64_prefix"
    do_make
    do_make_install
    sed -i.bak 's/-llensfun/-llensfun -lstdc++/' "$PKG_CONFIG_PATH/lensfun.pc"
    unset CMAKE_STATIC_LINKER_FLAGS
  cd ..
}

```
